### PR TITLE
Add module and configuration documentation

### PR DESCRIPTION
**Pull request by rimi-itk**
# Link to issue

@todo

# Description

Adds documentation on modules and documentation.

# Checklist

- [x] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [x] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [x] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

### CODE REVIEW

**Review by Anna-itk — CHANGES_REQUESTED** [review]
Did you check if the Readme's of the different modules were sufficient or did you just link them?

**Comment by rimi-itk** [comment]
@Anna-itk, in the first iteration I basically just link to the `README.md` files in the modules, but in the second iteration I will actually go through the contents of the files and make any necessary improvements.

**Review by Anna-itk — APPROVED** [review]
Thanks for clarifying.

**Review by Anna-itk — APPROVED** [review]
Beautiful!

**Pull request merged**
